# docker-compose.yaml
version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:2.362-alpine-jdk17 # alpine = smallest size
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
